name: quantstl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - joblib
  - numpy
  - scipy
  - opencv
  - pip:
    - opencv-python
    - scikit-learn
    - sklearn==0.0
    - streamlit