name: quantstl
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - cffi=1.15.1
  - click=8.0.4
  - colorama=0.4.5
  - cryptography=37.0.1
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - fftw=3.3.9
  - fonttools=4.25.0
  - freetype=2.10.4
  - glib=2.69.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.4.0
  - kiwisolver=1.4.2
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.4.0
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclassic=0.3.5
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - nest-asyncio=1.5.5
  - nltk=3.7
  - numexpr=2.8.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.3.5
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.1.2
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - psutil=5.9.0
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.7.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - pytz=2022.1
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.3.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - regex=2022.7.9
  - scipy=1.7.3
  - seaborn=0.11.2
  - send2trash=1.8.0
  - setuptools=63.4.1
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - sqlite=3.39.2
  - terminado=0.13.1
  - testpath=0.6.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - tqdm=4.64.0
  - traitlets=5.1.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - aiosignal==1.2.0
    - altair==4.2.0
    - backports-zoneinfo==0.2.1
    - blinker==1.5
    - cachetools==5.2.1
    - charset-normalizer==2.0.12
    - commonmark==0.9.1
    - distlib==0.3.4
    - et-xmlfile==1.1.0
    - filelock==3.7.1
    - frozenlist==1.3.0
    - gitdb==4.0.10
    - gitpython==3.1.30
    - grpcio==1.43.0
    - imbalanced-learn==0.8.1
    - msgpack==1.0.4
    - opencv-python==4.5.3.56
    - openpyxl==3.0.9
    - platformdirs==2.5.2
    - protobuf==3.20.1
    - pyarrow==10.0.1
    - pydeck==0.8.0
    - pympler==1.0.1
    - pypcapfile==0.12.0
    - pytz-deprecation-shim==0.1.0.post0
    - pyyaml==6.0
    - rawpy==0.17.0
    - ray==1.13.0
    - requests==2.28.0
    - rich==13.1.0
    - scikit-learn==1.0.1
    - semver==2.13.0
    - sklearn==0.0
    - smmap==5.0.0
    - streamlit==1.17.0
    - tabulate==0.8.10
    - tensorboardx==2.5.1
    - tifffile==2021.10.10
    - toolz==0.12.0
    - tzdata==2022.7
    - tzlocal==4.2
    - urllib3==1.26.9
    - validators==0.20.0
    - virtualenv==20.15.0
    - watchdog==2.2.1
    - xlrd==2.0.1